# -*- coding: utf-8 -*-
"""cleaning project 2. ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GdxRE8FMOiNKF7tMSv0HoZU8Iz34CoGE
"""

import pandas as pd
import numpy as np

file_path = "/content/Global_Inflation_2000_2025_DIRTY.xlsx"

excel_file = pd.ExcelFile(file_path)

excel_file.sheet_names

df=pd.read_excel("/content/Global_Inflation_2000_2025_DIRTY.xlsx",sheet_name="Country (2)")

df.info()

df.head()

df.isnull().sum()

df.duplicated().sum()

df[df["Country_ID"].duplicated(keep=False)]

df= df.drop_duplicates()

df = df.sort_values(by=['Country_ID', 'Country_Name'], na_position='last')

df = df.drop_duplicates(subset=['Country_ID'], keep='first')

print("Duplicates in Country_ID:", df['Country_ID'].duplicated().sum())
print("\nMissing values remaining:")
print(df.isnull().sum())

df[df['Country_Code'].isnull() | df['Country_Name'].isnull()]

code_to_name = {
    'BWA': 'Botswana',
    'COG': 'Congo, Rep.',
    'ITA': 'Italy',
    'NER': 'Niger',
    'SUR': 'Suriname',
    'XKX': 'Kosovo'
}
name_to_code = {
    'Algeria': 'DZA',
    'France': 'FRA',
    'Libya': 'LBY',
    'St. Lucia': 'LCA',
    'Togo': 'TGO'
}
df['Country_Name'] = df['Country_Name'].fillna(df['Country_Code'].map(code_to_name))

df['Country_Code'] = df['Country_Code'].fillna(df['Country_Name'].map(name_to_code))

df

df=df.reset_index(drop=True)
df["Country_ID"]="c-"+(df.index+1).astype(str).str.zfill(6)

for col in ["Country_Code","Country_Name","Country_ID"]:
  df[col]=df[col].astype("string")

df.info()

df2=pd.read_excel("/content/Global_Inflation_2000_2025_DIRTY.xlsx",sheet_name="Date (2)")

df2

df2.duplicated().sum()

df2.info()

df2.isnull().sum()

df2["Date"] = pd.to_datetime(df2["Date"], errors="coerce")

df2["Quarter"] = df2["Quarter"].astype("string").str.strip().str.upper()

df2["Quarter"] = df2["Quarter"].replace({
    "q1": "Q1",
    "1Q": "Q1",
    "QUARTER 1": "Q1",
    "2Q": "Q2",
    "QUARTER 2": "Q2",
    "3Q": "Q3",
    "QUARTER 3": "Q3",
    "4Q": "Q4",
    "QUARTER 4": "Q4"
})

df2["Quarter"].value_counts(dropna=False)

df2.loc[df2["Quarter"].isna(), "Quarter"] = "Q" + df2.loc[df2["Quarter"].isna(), "Date"].dt.quarter.astype(str)

df2["Quarter"].isna().sum()

df2["Quarter"].value_counts(dropna=False)

df2

df2["Date_ID"] = df2["Date_ID"].astype("string")

df2["Date"] = pd.to_datetime(df2["Date"], errors="coerce")

df2[df2["Date"].isna()][["Date_ID", "Date", "Year", "Month", "Month_Name", "Quarter"]]

date_number = df2["Date_ID"].str.extract(r"(\d+)")[0].astype("int")

df2["Date"] = pd.to_datetime("2000-01-01") + pd.offsets.MonthBegin(0)
df2["Date"] = [
    pd.Timestamp("2000-01-01") + pd.DateOffset(months=n-1)
    for n in date_number
]

df2["Date"] = pd.to_datetime(df2["Date"], errors="coerce")

df2.head()

df2["Date"] = pd.to_datetime(
    dict(
        year=df2["Year"],
        month=df2["Month"],
        day=1
    ),
    errors="coerce"
)

df2["Date"].isna().sum()

df2[df2["Date"].isna()]

df2["Date"] = df2["Date_ID"].str.extract(r"(\d+)")[0].astype(int).apply(
    lambda n: pd.Timestamp("2000-01-01") + pd.DateOffset(months=n-1)
)

df2["Date"].isna().sum()

df2['Year'] = df2['Year'].astype('Int64')
df2['Month'] = df2['Month'].astype('Int64')

df2[['Year', 'Month', 'Month_Name']] = df2[['Year', 'Month', 'Month_Name']].ffill()

df2['Year'] = df2['Year'].astype(int)
df2['Month'] = df2['Month'].astype(int)

df2['Date'] = df2['Date'].astype('string')
df2['Month_Name'] = df2['Month_Name'].astype('string')

df2

df2 = df2.drop_duplicates(subset=['Year', 'Month'], keep='first').reset_index(drop=True)

df2['Date_ID'] = 'D-' + (df2.index + 1).astype(str).str.zfill(6)

df2

df3=pd.read_excel("/content/Global_Inflation_2000_2025_DIRTY.xlsx",sheet_name="Global_Inflation (2)")

df3.head()

df3

df3.duplicated().sum()

df3=df3.drop_duplicates()

df3.duplicated().sum()

df3.isnull().sum()

df3.info()

num_cols = ['HCPI', 'Food_CPI', 'Energy_CPI', 'PPI',
            'HCPI_available', 'Food_CPI_available', 'Energy_CPI_available', 'Core_CPI_available', 'PPI_available']

df3[num_cols] = df3[num_cols].fillna(0)

avail_cols = ['HCPI_available', 'Food_CPI_available', 'Energy_CPI_available', 'Core_CPI_available', 'PPI_available']

for col in avail_cols:
    df3[col] = df3[col].replace({0: 'FALSE', 1: 'TRUE', 0.0: 'FALSE', 1.0: 'TRUE'})

df3['Inflation_Category'] = df3['Inflation_Category'].fillna('Unknown')

df3.isnull().sum()

df3['COVID'] = df3['COVID'].ffill()

df3['Date_ID'] = df3['Date_ID'].ffill()
df3['Country_ID'] = df3['Country_ID'].ffill()

cols_to_round = ["HCPI","Food_CPI","Energy_CPI","PPI"]
df3[cols_to_round]=df3[cols_to_round].round(3)

df3.head()

df3['COVID'] = df3['COVID'].astype(str).str.replace('Pre-Covid', 'Pre-COVID', case=False)
df3['COVID'] = (
    df3['COVID']
    .astype(str)
    .str.replace('pre-covid', 'Pre-COVID', case=False)
    .str.replace('post-covid', 'Post-COVID', case=False)

)

df3.loc[df3["Energy_CPI"] == 0, "Energy_CPI_available"] = False

df3.loc[df3["Energy_CPI"] != 0, "Energy_CPI_available"] = True

file_name = 'cleaned data project python2.xlsx'
with pd.ExcelWriter(file_name, engine='openpyxl') as writer:
    df.to_excel(writer, sheet_name='Country', index=False)
    df2.to_excel(writer, sheet_name='Date', index=False)
    df3.to_excel(writer, sheet_name='Global_Inflation', index=False)